### ISSUE TITLE
Unable to run java sample in android.

### ISSUE THREAD

**Issue by michaelk-1234** [toitware/demos#32]
I've tried to check the possibility of using the toit SDK ('io.toit.api:toit-api:v0.11.2') in android. There are no problems with flutter. The toit_api 1.0.0 package on dart can be used. But in java, a similar experiment did not pass. I chose the example given here, which allows to login and get a list of devices. Android java application can be built, but at the execution stage the very first operation: the creation of the client object leads to crash. Sorry for the long trace log.

```
2022-03-17 07:31:19.436 19485-19485/? W/Zygote: Unable to open libbeluga.so: dlopen failed: library "libbeluga.so" not found.
2022-03-17 07:31:19.454 19485-19485/? I/xample.toitjav: Late-enabling -Xcheck:jni
2022-03-17 07:31:19.468 19485-19485/? I/xample.toitjav: Unquickening 21 vdex files!
2022-03-17 07:31:19.832 19485-19485/com.example.toitjava I/Perf: Connecting to perf service.
2022-03-17 07:31:19.839 19485-19485/com.example.toitjava D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-03-17 07:31:19.840 19485-19485/com.example.toitjava D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-03-17 07:31:19.899 19485-19485/com.example.toitjava D/DecorView[]: getWindowModeFromSystem  windowmode is 1
2022-03-17 07:31:19.899 19485-19485/com.example.toitjava D/DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
2022-03-17 07:31:19.933 19485-19485/com.example.toitjava W/xample.toitjav: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2022-03-17 07:31:19.933 19485-19485/com.example.toitjava W/xample.toitjav: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2022-03-17 07:31:19.989 19485-19485/com.example.toitjava W/Looper: PerfMonitor looperActivity : package=com.example.toitjava/.MainActivity time=139ms latency=334ms running=128ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem } historyMsgCount=3 (msgIndex=3 wall=331ms seq=3 running=316ms runnable=7ms io=1ms binder=10ms late=4ms h=android.app.ActivityThread$H w=110)
2022-03-17 07:31:19.990 19485-19485/com.example.toitjava W/Looper: PerfMonitor looperActivity : package=com.example.toitjava/.MainActivity time=0ms latency=472ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=4 (msgIndex=3 wall=331ms seq=3 running=316ms runnable=7ms io=1ms binder=10ms late=4ms h=android.app.ActivityThread$H w=110) (msgIndex=4 wall=139ms seq=4 running=128ms runnable=2ms io=2ms binder=11ms late=334ms h=android.app.ActivityThread$H w=159)
2022-03-17 07:31:20.009 19485-19593/com.example.toitjava I/AdrenoGLES-0: QUALCOMM build                   : 42297a4, I9e9b240040
    Build Date                       : 03/19/21
    OpenGL ES Shader Compiler Version: EV031.32.02.07
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.9.1.R1.11.00.00.604.070
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2022-03-17 07:31:20.009 19485-19593/com.example.toitjava I/AdrenoGLES-0: Build Config                     : S P 10.0.6 AArch64
2022-03-17 07:31:20.009 19485-19593/com.example.toitjava I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2022-03-17 07:31:20.013 19485-19593/com.example.toitjava I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
2022-03-17 07:31:27.848 19485-19589/com.example.toitjava I/xample.toitjav: ProcessProfilingInfo new_methods=1570 is saved saved_to_disk=1 resolve_classes_delay=8000
2022-03-17 07:31:37.393 19485-19485/com.example.toitjava V/MiuiFrameworkFactory: get AllImpl object = android.common.MiuiFrameworkFactoryImpl@16268c9
2022-03-17 07:31:37.398 19485-19485/com.example.toitjava W/MirrorManager: this model don't Support
2022-03-17 07:31:37.539 19485-19485/com.example.toitjava I/GrpcSslContexts: Java 9 ALPN API unavailable (this may be normal)
2022-03-17 07:31:37.540 19485-19485/com.example.toitjava I/GrpcSslContexts: netty-tcnative unavailable (this may be normal)
    java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLContext
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:123)
        at io.netty.handler.ssl.OpenSsl.isAvailable(OpenSsl.java:437)
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:217)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
        at com.example.toitjava.Client.<clinit>(Client.java:17)
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36)
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12)
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29)
        at android.view.View.performClick(View.java:7509)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7486)
        at android.view.View.access$3600(View.java:841)
        at android.view.View$PerformClick.run(View.java:28720)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.netty.internal.tcnative.SSLContext" on path: DexPathList[[zip file "/data/app/~~PFfE4ZIJZIfyFLbq9RWWZQ==/com.example.toitjava-HZr4nXB_8kaCrJgjxlNw3g==/base.apk"],nativeLibraryDirectories=[/data/app/~~PFfE4ZIJZIfyFLbq9RWWZQ==/com.example.toitjava-HZr4nXB_8kaCrJgjxlNw3g==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:123) 
        at io.netty.handler.ssl.OpenSsl.isAvailable(OpenSsl.java:437) 
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:217) 
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144) 
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93) 
        at com.example.toitjava.Client.<clinit>(Client.java:17) 
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36) 
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12) 
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29) 
        at android.view.View.performClick(View.java:7509) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131) 
        at android.view.View.performClickInternal(View.java:7486) 
        at android.view.View.access$3600(View.java:841) 
        at android.view.View$PerformClick.run(View.java:28720) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8056) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
2022-03-17 07:31:37.541 19485-19485/com.example.toitjava I/GrpcSslContexts: Conscrypt not found (this may be normal)
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at io.grpc.internal.ConscryptLoader.newProvider(ConscryptLoader.java:78)
        at io.grpc.netty.GrpcSslContexts$ConscryptHolder.<clinit>(GrpcSslContexts.java:277)
        at io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:250)
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:221)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
        at com.example.toitjava.Client.<clinit>(Client.java:17)
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36)
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12)
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29)
        at android.view.View.performClick(View.java:7509)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7486)
        at android.view.View.access$3600(View.java:841)
        at android.view.View$PerformClick.run(View.java:28720)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libconscrypt_openjdk_jni-linux-aarch_64.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:297)
        at org.conscrypt.NativeLibraryLoader$1.run(NativeLibraryLoader.java:289)
        at java.security.AccessController.doPrivileged(AccessController.java:43)
        at org.conscrypt.NativeLibraryLoader.loadLibraryFromHelperClassloader(NativeLibraryLoader.java:289)
        at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:262)
        at org.conscrypt.NativeLibraryLoader.load(NativeLibraryLoader.java:162)
        at org.conscrypt.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:106)
        at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:50)
        at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:63)
        at org.conscrypt.NativeCrypto.checkAvailability(NativeCrypto.java:80)
        at org.conscrypt.Conscrypt.checkAvailability(Conscrypt.java:111)
        at org.conscrypt.Conscrypt.newProvider(Conscrypt.java:125)
        at java.lang.reflect.Method.invoke(Native Method) 
        at io.grpc.internal.ConscryptLoader.newProvider(ConscryptLoader.java:78) 
        at io.grpc.netty.GrpcSslContexts$ConscryptHolder.<clinit>(GrpcSslContexts.java:277) 
        at io.grpc.netty.GrpcSslContexts.findJdkProvider(GrpcSslContexts.java:250) 
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:221) 
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144) 
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93) 
        at com.example.toitjava.Client.<clinit>(Client.java:17) 
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36) 
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12) 
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29) 
        at android.view.View.performClick(View.java:7509) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131) 
        at android.view.View.performClickInternal(View.java:7486) 
        at android.view.View.access$3600(View.java:841) 
        at android.view.View$PerformClick.run(View.java:28720) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8056) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libconscrypt_openjdk_jni-linux-aarch_64.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
        at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
        at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
        		... 30 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libconscrypt_openjdk_jni.so" not found
    		... 40 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libconscrypt_openjdk_jni.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
2022-03-17 07:31:37.541 19485-19485/com.example.toitjava I/GrpcSslContexts:     at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
        at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
        		... 30 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libconscrypt.so" not found
    		... 40 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libconscrypt.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.conscrypt.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:54)
        at org.conscrypt.NativeLibraryLoader.loadLibraryFromCurrentClassloader(NativeLibraryLoader.java:318)
        at org.conscrypt.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:273)
        		... 30 more
2022-03-17 07:31:37.542 19485-19485/com.example.toitjava I/GrpcSslContexts: Jetty ALPN unavailable (this may be normal)
    java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64)
        at io.grpc.netty.JettyTlsUtil.getJettyAlpnUnavailabilityCause(JettyTlsUtil.java:76)
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:232)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
        at com.example.toitjava.Client.<clinit>(Client.java:17)
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36)
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12)
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29)
        at android.view.View.performClick(View.java:7509)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7486)
        at android.view.View.access$3600(View.java:841)
        at android.view.View$PerformClick.run(View.java:28720)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.alpn.ALPN
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1358)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:64) 
        at io.grpc.netty.JettyTlsUtil.getJettyAlpnUnavailabilityCause(JettyTlsUtil.java:76) 
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:232) 
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144) 
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93) 
        at com.example.toitjava.Client.<clinit>(Client.java:17) 
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36) 
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12) 
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29) 
        at android.view.View.performClick(View.java:7509) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131) 
        at android.view.View.performClickInternal(View.java:7486) 
        at android.view.View.access$3600(View.java:841) 
        at android.view.View$PerformClick.run(View.java:28720) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8056) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
2022-03-17 07:31:37.542 19485-19485/com.example.toitjava D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2022-03-17 07:31:37.543 19485-19485/com.example.toitjava E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.toitjava, PID: 19485
    java.lang.ExceptionInInitializerError
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36)
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12)
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29)
        at android.view.View.performClick(View.java:7509)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131)
        at android.view.View.performClickInternal(View.java:7486)
        at android.view.View.access$3600(View.java:841)
        at android.view.View$PerformClick.run(View.java:28720)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:233)
        at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
        at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
        at com.example.toitjava.Client.<clinit>(Client.java:17)
        at com.example.toitjava.MainActivity.createClient(MainActivity.java:36) 
        at com.example.toitjava.MainActivity.access$000(MainActivity.java:12) 
        at com.example.toitjava.MainActivity$1.onClick(MainActivity.java:29) 
        at android.view.View.performClick(View.java:7509) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1131) 
        at android.view.View.performClickInternal(View.java:7486) 
        at android.view.View.access$3600(View.java:841) 
        at android.view.View$PerformClick.run(View.java:28720) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8056) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
2022-03-17 07:31:37.584 19485-19485/com.example.toitjava I/Process: Sending signal. PID: 19485 SIG: 9

```

**Comment by floitsch** [comment]
Unfortunately this is not something we can easily help.
I tried for some time to get it running, but I'm not a Java/Android expert and didn't make any progress.
Since the package works with Java, it feels like this is an Android packaging problem, so I guess there isn't actually anything we need to change from our side.

If you manage to get it working please let us know, though.
